import os
import httpx
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)

class HuggingFaceClient:
    def __init__(self):
        self.api_key = os.getenv("HUGGINGFACE_API_KEY")
        if not self.api_key:
            logger.warning("HUGGINGFACE_API_KEY environment variable not set. Real inference will fail.")
        
        self.base_url = "https://api-inference.huggingface.co/models"

    async def generate_text(self, model_id: str, prompt: str, max_tokens: int = 100, temperature: float = 0.7) -> Dict[str, Any]:
        """
        Calls the Hugging Face Inference API for a specific model.
        """
        url = f"{self.base_url}/{model_id}"
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        
        # Adjust payload based on standard text-generation / conversational endpoints
        payload = {
            "inputs": prompt,
            "parameters": {
                "max_new_tokens": max_tokens,
                "temperature": temperature,
                "return_full_text": False
            }
        }
        
        async with httpx.AsyncClient() as client:
            try:
                if not self.api_key:
                    # Mock Response Logic for learning/replication projects
                    import asyncio
                    import random
                    await asyncio.sleep(0.8 + random.random() * 1.5) # Simulate network + inference latency
                    
                    if "code" in prompt.lower() or "python" in prompt.lower():
                        mock_text = f"// [Mock Response from {model_id}]\n\ndef mock_solution():\n    # This is a simulated response for prompt: \"{prompt[:30]}...\"\n    return \"In a real deployment, this would be generated by a fine-tuned coding model.\""
                    else:
                        mock_text = f"[Inference Simulated: {model_id}]\n\nYou asked: \"{prompt[:50]}...\"\n\nResponse: This is a placeholder response. In a production environment with a valid HUGGINGFACE_API_KEY, the gateway would route this request to the {model_id} endpoint and return a real-time completion. This replication demonstrates the full end-to-end request/response cycle."

                    return {"text": mock_text, "status": "success"}

                response = await client.post(url, headers=headers, json=payload, timeout=30.0)
                response.raise_for_status()
                result = response.json()
                
                # Extract text based on standard HF completion format
                if isinstance(result, list) and len(result) > 0 and 'generated_text' in result[0]:
                    return {"text": result[0]['generated_text'].strip(), "status": "success"}
                else:
                    # Fallback
                    return {"text": str(result), "status": "success"}
                    
            except httpx.HTTPStatusError as e:
                logger.error(f"HF API HTTP error: {e.response.status_code} - {e.response.text}")
                return {"error": f"API Error: {e.response.status_code}", "status": "error"}
            except Exception as e:
                logger.error(f"HF API connection error: {str(e)}")
                return {"error": f"Connection Error: {str(e)}", "status": "error"}
